from __future__ import annotations

import sys
import unittest
import json
import tempfile
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parents[1]))

from app.core.runtime.agent_skill_input_generation import (
    build_skill_input_system_prompt,
    build_skill_input_user_prompt,
    generate_agent_skill_inputs,
)
from app.core.runtime.structured_output import schema_for_skill_io_field
from app.core.runtime.skill_bindings import ResolvedAgentSkillBinding
from app.core.schemas.node_system import NodeSystemAgentNode, NodeSystemAgentSkillBinding, NodeSystemStateDefinition, NodeSystemStateType
from app.core.schemas.skills import SkillDefinition, SkillIoField
from app.core.storage.skill_artifact_store import create_uploaded_skill_artifact, resolve_skill_artifact_path


class AgentSkillInputGenerationTests(unittest.TestCase):
    def test_skill_text_array_value_type_builds_string_array_schema(self) -> None:
        schema = schema_for_skill_io_field(
            SkillIoField(
                key="commands",
                name="Commands",
                valueType="text_array",
                description="Page operation commands generated by the LLM.",
            )
        )

        self.assertEqual(schema["type"], "array")
        self.assertEqual(schema["items"]["type"], "string")
        self.assertIn("Page operation commands", schema["description"])

    def test_skill_input_prompt_uses_llm_instruction_protocol_field(self) -> None:
        prompt = build_skill_input_system_prompt(
            input_values={"question": "latest release"},
            bindings=[
                ResolvedAgentSkillBinding(
                    binding=NodeSystemAgentSkillBinding(skillKey="web_search"),
                    source="node_config",
                )
            ],
            skill_definitions={
                "web_search": SkillDefinition(
                    skillKey="web_search",
                    name="Web Search",
                    llmInstruction="Generate a query and run the skill without summarizing results.",
                    llmOutputSchema=[SkillIoField(key="query", name="Query", valueType="text")],
                )
            },
        )

        self.assertIn("llmInstruction: Generate a query", prompt)
        self.assertNotIn("agentInstruction", prompt)

    def test_skill_input_prompt_separates_state_inputs_from_llm_parameters(self) -> None:
        prompt = build_skill_input_system_prompt(
            input_values={"user_goal": "打开运行历史"},
            bindings=[
                ResolvedAgentSkillBinding(
                    binding=NodeSystemAgentSkillBinding(skillKey="toograph_page_operator"),
                    source="node_config",
                )
            ],
            skill_definitions={
                "toograph_page_operator": SkillDefinition(
                    skillKey="toograph_page_operator",
                    name="TooGraph Page Operator",
                    stateInputSchema=[
                        SkillIoField(
                            key="user_goal",
                            name="User Goal",
                            valueType="text",
                            description="User goal read from graph state.",
                        )
                    ],
                    llmOutputSchema=[
                        SkillIoField(
                            key="commands",
                            name="Commands",
                            valueType="json",
                            description="Page operation commands generated by the LLM.",
                        )
                    ],
                )
            },
        )

        self.assertIn("stateInputSchema:", prompt)
        self.assertIn("description: User goal read from graph state.", prompt)
        self.assertIn("llmOutputSchema:", prompt)
        self.assertIn("description: Page operation commands generated by the LLM.", prompt)

    def test_skill_input_prompt_includes_before_llm_context(self) -> None:
        with tempfile.TemporaryDirectory() as temp_dir:
            skill_dir = Path(temp_dir) / "web_search"
            skill_dir.mkdir()
            (skill_dir / "before_llm.py").write_text(
                "import json\n"
                "print(json.dumps({'context': 'Current date: 2026-05-08'}))\n",
                encoding="utf-8",
            )
            prompt = build_skill_input_system_prompt(
                input_values={"question": "最新模型发布日期"},
                bindings=[
                    ResolvedAgentSkillBinding(
                        binding=NodeSystemAgentSkillBinding(skillKey="web_search"),
                        source="node_config",
                    )
                ],
                skill_definitions={
                    "web_search": SkillDefinition(
                        skillKey="web_search",
                        name="Web Search",
                        llmInstruction="Generate a query.",
                        llmOutputSchema=[SkillIoField(key="query", name="Query", valueType="text")],
                        sourcePath=str(skill_dir / "skill.json"),
                    )
                },
            )

        self.assertIn("== Skill Pre-LLM Context ==", prompt)
        self.assertIn("skillKey: web_search", prompt)
        self.assertIn("Current date: 2026-05-08", prompt)

    def test_before_llm_receives_runtime_context_without_graph_state(self) -> None:
        with tempfile.TemporaryDirectory() as temp_dir:
            skill_dir = Path(temp_dir) / "toograph_page_operator"
            skill_dir.mkdir()
            (skill_dir / "before_llm.py").write_text(
                "import json, sys\n"
                "payload = json.loads(sys.stdin.read() or '{}')\n"
                "context = {\n"
                "  'has_graph_state': 'graph_state' in payload,\n"
                "  'page_path': payload.get('runtime_context', {}).get('page_path'),\n"
                "}\n"
                "print(json.dumps({'context': json.dumps(context, ensure_ascii=False)}))\n",
                encoding="utf-8",
            )
            prompt = build_skill_input_system_prompt(
                input_values={"page_path": "/stale-graph-state"},
                bindings=[
                    ResolvedAgentSkillBinding(
                        binding=NodeSystemAgentSkillBinding(skillKey="toograph_page_operator"),
                        source="node_config",
                    )
                ],
                skill_definitions={
                    "toograph_page_operator": SkillDefinition(
                        skillKey="toograph_page_operator",
                        name="TooGraph Page Operator",
                        llmOutputSchema=[SkillIoField(key="commands", name="Commands", valueType="json")],
                        sourcePath=str(skill_dir / "skill.json"),
                    )
                },
                runtime_context={"page_path": "/editor"},
            )

        before_llm_context = prompt.split("== Skill Pre-LLM Context ==", 1)[1]
        self.assertIn('"has_graph_state": false', before_llm_context)
        self.assertIn('"page_path": "/editor"', before_llm_context)
        self.assertNotIn("/stale-graph-state", before_llm_context)

    def test_skill_input_prompt_passes_node_task_instruction_to_before_llm(self) -> None:
        with tempfile.TemporaryDirectory() as temp_dir:
            skill_dir = Path(temp_dir) / "local_workspace_executor"
            skill_dir.mkdir()
            (skill_dir / "before_llm.py").write_text(
                "import json, sys\n"
                "payload = json.loads(sys.stdin.read() or '{}')\n"
                "print(json.dumps({'context': payload.get('task_instruction', '')}))\n",
                encoding="utf-8",
            )
            node = NodeSystemAgentNode.model_validate(
                {
                    "kind": "agent",
                    "ui": {"position": {"x": 0, "y": 0}},
                    "config": {
                        "skillKey": "local_workspace_executor",
                        "taskInstruction": "写入 backend/data/tmp/example.txt。",
                    },
                }
            )
            prompt = build_skill_input_system_prompt(
                input_values={},
                bindings=[
                    ResolvedAgentSkillBinding(
                        binding=NodeSystemAgentSkillBinding(skillKey="local_workspace_executor"),
                        source="node_config",
                    )
                ],
                skill_definitions={
                    "local_workspace_executor": SkillDefinition(
                        skillKey="local_workspace_executor",
                        name="Local Workspace Executor",
                        llmOutputSchema=[SkillIoField(key="path", name="Path", valueType="text")],
                        sourcePath=str(skill_dir / "skill.json"),
                    )
                },
                node=node,
            )

        self.assertIn("写入 backend/data/tmp/example.txt。", prompt)

    def test_capability_selector_prompt_uses_before_llm_context_for_catalog(self) -> None:
        with tempfile.TemporaryDirectory() as temp_dir:
            skill_dir = Path(temp_dir) / "toograph_capability_selector"
            skill_dir.mkdir()
            (skill_dir / "before_llm.py").write_text(
                "import json\n"
                "print(json.dumps({'context': 'Available TooGraph capabilities:\\n"
                "Graph Templates:\\n- kind: subgraph\\n  key: advanced_web_research_loop\\n"
                "Skills:\\n- kind: skill\\n  key: web_search'}))\n",
                encoding="utf-8",
            )
            prompt = build_skill_input_system_prompt(
                input_values={"requirement": "帮我联网搜索资料"},
                bindings=[
                    ResolvedAgentSkillBinding(
                        binding=NodeSystemAgentSkillBinding(skillKey="toograph_capability_selector"),
                        source="node_config",
                    )
                ],
                skill_definitions={
                    "toograph_capability_selector": SkillDefinition(
                        skillKey="toograph_capability_selector",
                        name="TooGraph Capability Selector",
                        llmOutputSchema=[
                            SkillIoField(key="requirement", name="Requirement", valueType="text"),
                            SkillIoField(key="capability", name="Capability", valueType="capability"),
                        ],
                        stateOutputSchema=[SkillIoField(key="capability", name="Capability", valueType="capability")],
                        sourcePath=str(skill_dir / "skill.json"),
                        runtimeReady=True,
                        runtimeRegistered=True,
                    )
                },
            )

        self.assertIn("== Skill Pre-LLM Context ==", prompt)
        self.assertIn("Available TooGraph capabilities:", prompt)
        self.assertIn("key: advanced_web_research_loop", prompt)
        self.assertIn("key: web_search", prompt)
        self.assertNotIn("== Available Capabilities ==", prompt)

    def test_skill_input_prompt_uses_node_override_as_single_effective_instruction(self) -> None:
        node = NodeSystemAgentNode.model_validate(
            {
                "kind": "agent",
                "ui": {"position": {"x": 0, "y": 0}},
                "config": {
                    "skillKey": "web_search",
                    "taskInstruction": "Generate the search arguments.",
                    "skillInstructionBlocks": {
                        "web_search": {
                            "skillKey": "web_search",
                            "title": "联网搜索 skill instruction",
                            "content": "Use the user-edited query rule.",
                            "source": "node.override",
                        }
                    },
                },
            }
        )

        system_prompt = build_skill_input_system_prompt(
            input_values={"question": "latest release"},
            bindings=[
                ResolvedAgentSkillBinding(
                    binding=NodeSystemAgentSkillBinding(skillKey="web_search"),
                    source="node_config",
                )
            ],
            skill_definitions={
                "web_search": SkillDefinition(
                    skillKey="web_search",
                    name="Web Search",
                    llmInstruction="Use the manifest query rule.",
                    llmOutputSchema=[SkillIoField(key="query", name="Query", valueType="text")],
                )
            },
            node=node,
        )
        user_prompt = build_skill_input_user_prompt(node)

        self.assertIn("llmInstruction: Use the user-edited query rule.", system_prompt)
        self.assertNotIn("Use the manifest query rule.", system_prompt)
        self.assertEqual(user_prompt, "Generate the search arguments.")
        self.assertNotIn("Bound Skill Instructions", user_prompt)

    def test_skill_input_prompt_respects_blank_node_override(self) -> None:
        node = NodeSystemAgentNode.model_validate(
            {
                "kind": "agent",
                "ui": {"position": {"x": 0, "y": 0}},
                "config": {
                    "skillKey": "web_search",
                    "skillInstructionBlocks": {
                        "web_search": {
                            "skillKey": "web_search",
                            "title": "联网搜索 skill instruction",
                            "content": "   ",
                            "source": "node.override",
                        }
                    },
                },
            }
        )

        system_prompt = build_skill_input_system_prompt(
            input_values={"question": "latest release"},
            bindings=[
                ResolvedAgentSkillBinding(
                    binding=NodeSystemAgentSkillBinding(skillKey="web_search"),
                    source="node_config",
                )
            ],
            skill_definitions={
                "web_search": SkillDefinition(
                    skillKey="web_search",
                    name="Web Search",
                    llmInstruction="Use the manifest query rule.",
                    llmOutputSchema=[SkillIoField(key="query", name="Query", valueType="text")],
                )
            },
            node=node,
        )

        self.assertNotIn("Use the manifest query rule.", system_prompt)
        self.assertNotIn("llmInstruction:", system_prompt)

    def test_skill_input_prompt_does_not_expose_output_mapping_to_llm(self) -> None:
        prompt = build_skill_input_system_prompt(
            input_values={"question": "latest release"},
            bindings=[
                ResolvedAgentSkillBinding(
                    binding=NodeSystemAgentSkillBinding(
                        skillKey="web_search",
                        outputMapping={
                            "query": "planned_query",
                            "source_urls": "search_sources",
                        },
                    ),
                    source="node_config",
                )
            ],
            skill_definitions={
                "web_search": SkillDefinition(
                    skillKey="web_search",
                    name="Web Search",
                    llmOutputSchema=[SkillIoField(key="query", name="Query", valueType="text")],
                    stateOutputSchema=[
                        SkillIoField(key="query", name="Query", valueType="text", description="Executed query."),
                        SkillIoField(key="source_urls", name="Source URLs", valueType="json", description="Original URLs."),
                    ],
                )
            },
            state_schema={
                "planned_query": NodeSystemStateDefinition(
                    name="联网搜索 Query",
                    description="实际交给搜索技能执行的查询语句。",
                    type=NodeSystemStateType.TEXT,
                ),
                "search_sources": NodeSystemStateDefinition(
                    name="联网搜索 Source URLs",
                    description="搜索技能返回的原文网页 URL 列表。",
                    type=NodeSystemStateType.JSON,
                ),
            },
        )

        self.assertNotIn("== Bound Skill Output Mapping ==", prompt)
        self.assertNotIn("outputKey: query", prompt)
        self.assertNotIn("targetState: planned_query", prompt)
        self.assertNotIn("targetName: 联网搜索 Query", prompt)
        self.assertIn("== Skill LLM Output JSON Shape ==", prompt)
        self.assertIn('"web_search"', prompt)
        self.assertIn('"query"', prompt)

    def test_skill_input_prompt_expands_result_package_inputs_before_planning_arguments(self) -> None:
        artifact = create_uploaded_skill_artifact(
            file_name="search-source.md",
            content_type="text/markdown",
            payload=b"Downloaded source text for the next skill input.",
        )
        try:
            prompt = build_skill_input_system_prompt(
                input_values={
                    "search_result": {
                        "kind": "result_package",
                        "sourceType": "skill",
                        "sourceKey": "web_search",
                        "outputs": {
                            "artifact_paths": {
                                "name": "Artifact Paths",
                                "description": "Downloaded source documents.",
                                "type": "file",
                                "value": [artifact["local_path"]],
                            }
                        },
                    }
                },
                bindings=[
                    ResolvedAgentSkillBinding(
                        binding=NodeSystemAgentSkillBinding(skillKey="extract_facts"),
                        source="node_config",
                    )
                ],
                skill_definitions={
                    "extract_facts": SkillDefinition(
                        skillKey="extract_facts",
                        name="Extract Facts",
                        llmOutputSchema=[SkillIoField(key="document_summary", name="Document Summary", valueType="text")],
                    )
                },
                state_schema={
                    "search_result": NodeSystemStateDefinition.model_validate(
                        {
                            "name": "Search Result",
                            "type": "result_package",
                        }
                    )
                },
            )

            self.assertIn("key: artifact_paths", prompt)
            self.assertIn("type: file", prompt)
            self.assertIn("Downloaded source text for the next skill input.", prompt)
            self.assertNotIn(artifact["local_path"], prompt)
        finally:
            resolve_skill_artifact_path(artifact["local_path"]).unlink(missing_ok=True)

    def test_generate_skill_inputs_passes_structured_output_schema_to_model(self) -> None:
        captured: dict[str, object] = {}

        def chat_with_local_model_with_meta_func(**kwargs):
            captured.update(kwargs)
            return ('{"web_search": {"query": "TooGraph structured output", "search_context": ""}}', {"warnings": []})

        node = NodeSystemAgentNode.model_validate(
            {
                "kind": "agent",
                "ui": {"position": {"x": 0, "y": 0}},
                "config": {
                    "skillKey": "web_search",
                    "taskInstruction": "Build search arguments.",
                },
            }
        )

        skill_inputs, _reasoning, warnings, updated_config = generate_agent_skill_inputs(
            node=node,
            input_values={"question": "How should LLM nodes emit JSON?"},
            bindings=[
                ResolvedAgentSkillBinding(
                    binding=NodeSystemAgentSkillBinding(skillKey="web_search"),
                    source="node_config",
                )
            ],
            skill_definitions={
                "web_search": SkillDefinition(
                    skillKey="web_search",
                    name="Web Search",
                    llmOutputSchema=[
                        SkillIoField(
                            key="query",
                            name="Query",
                            valueType="text",
                            description="Search query.",
                        ),
                        SkillIoField(
                            key="search_context",
                            name="Search Context",
                            valueType="text",
                            description="Additional search context. Use an empty string when not needed.",
                        )
                    ],
                )
            },
            runtime_config={
                "resolved_provider_id": "local",
                "runtime_model_name": "test-model",
                "resolved_temperature": 0.2,
                "resolved_thinking": False,
                "resolved_thinking_level": "off",
            },
            chat_with_local_model_with_meta_func=chat_with_local_model_with_meta_func,
        )

        self.assertEqual(skill_inputs, {"web_search": {"query": "TooGraph structured output", "search_context": ""}})
        self.assertEqual(warnings, [])
        schema = captured["structured_output_schema"]
        self.assertEqual(schema["type"], "object")
        self.assertEqual(schema["required"], ["web_search"])
        self.assertFalse(schema["additionalProperties"])
        self.assertEqual(schema["properties"]["web_search"]["required"], ["query", "search_context"])
        self.assertFalse(schema["properties"]["web_search"]["additionalProperties"])
        self.assertEqual(schema["properties"]["web_search"]["properties"]["query"]["type"], "string")
        self.assertEqual(updated_config["skill_input_structured_output_strategy"], "json_schema")

    def test_repairs_invalid_skill_inputs_without_original_prompt_context(self) -> None:
        calls: list[dict[str, object]] = []

        def chat_with_local_model_with_meta_func(**kwargs):
            calls.append(dict(kwargs))
            if len(calls) == 1:
                return ('{"web_search": {"query": 7}}', {"warnings": [], "model": "test-model"})
            return ('{"web_search": {"query": "repaired query"}}', {"warnings": [], "model": "test-model"})

        node = NodeSystemAgentNode.model_validate(
            {
                "kind": "agent",
                "ui": {"position": {"x": 0, "y": 0}},
                "config": {
                    "skillKey": "web_search",
                    "taskInstruction": "ORIGINAL SKILL TASK",
                },
            }
        )

        skill_inputs, _reasoning, warnings, updated_config = generate_agent_skill_inputs(
            node=node,
            input_values={"question": "ORIGINAL SECRET INPUT"},
            bindings=[
                ResolvedAgentSkillBinding(
                    binding=NodeSystemAgentSkillBinding(skillKey="web_search"),
                    source="node_config",
                )
            ],
            skill_definitions={
                "web_search": SkillDefinition(
                    skillKey="web_search",
                    name="Web Search",
                    llmOutputSchema=[
                        SkillIoField(
                            key="query",
                            name="Query",
                            valueType="text",
                            description="Search query.",
                        )
                    ],
                )
            },
            runtime_config={
                "resolved_provider_id": "local",
                "runtime_model_name": "test-model",
                "resolved_temperature": 0.2,
                "resolved_thinking": False,
                "resolved_thinking_level": "off",
            },
            chat_with_local_model_with_meta_func=chat_with_local_model_with_meta_func,
        )

        self.assertEqual(skill_inputs, {"web_search": {"query": "repaired query"}})
        self.assertEqual(warnings, [])
        self.assertEqual(len(calls), 2)
        repair_call = calls[1]
        repair_prompt = f"{repair_call['system_prompt']}\n{repair_call['user_prompt']}"
        self.assertIn("JSON repair step", str(repair_call["system_prompt"]))
        self.assertIn("target_schema", str(repair_call["user_prompt"]))
        self.assertIn("validation_errors", str(repair_call["user_prompt"]))
        self.assertIn("raw_model_output", str(repair_call["user_prompt"]))
        repair_payload = json.loads(str(repair_call["user_prompt"]))
        self.assertEqual(repair_payload["raw_model_output"], '{"web_search": {"query": 7}}')
        self.assertNotIn("ORIGINAL SECRET INPUT", repair_prompt)
        self.assertNotIn("ORIGINAL SKILL TASK", repair_prompt)
        self.assertEqual(repair_call["thinking_level"], "off")
        self.assertTrue(updated_config["skill_input_structured_output_repair_attempted"])
        self.assertTrue(updated_config["skill_input_structured_output_repair_succeeded"])
        self.assertEqual(updated_config["skill_input_structured_output_validation_errors"], [])
        self.assertIn(
            "$.web_search.query expected string",
            updated_config["skill_input_structured_output_initial_validation_errors"][0],
        )


if __name__ == "__main__":
    unittest.main()
