from __future__ import annotations

import sys
import unittest
import json
import tempfile
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parents[1]))

from app.core.runtime.agent_action_input_generation import (
    build_action_input_system_prompt,
    build_action_input_user_prompt,
    generate_agent_action_inputs,
)
from app.core.runtime.structured_output import schema_for_action_io_field
from app.core.runtime.action_bindings import ResolvedAgentActionBinding
from app.core.schemas.node_system import NodeSystemAgentNode, NodeSystemAgentActionBinding, NodeSystemStateDefinition, NodeSystemStateType
from app.core.schemas.actions import ActionDefinition, ActionIoField
from app.core.storage.capability_artifact_store import create_uploaded_capability_artifact, resolve_capability_artifact_path


class AgentActionInputGenerationTests(unittest.TestCase):
    def test_action_text_array_value_type_builds_string_array_schema(self) -> None:
        schema = schema_for_action_io_field(
            ActionIoField(
                key="commands",
                name="Commands",
                valueType="text_array",
                description="Page operation commands generated by the LLM.",
            )
        )

        self.assertEqual(schema["type"], "array")
        self.assertEqual(schema["items"]["type"], "string")
        self.assertIn("Page operation commands", schema["description"])

    def test_action_input_prompt_uses_llm_instruction_protocol_field(self) -> None:
        prompt = build_action_input_system_prompt(
            input_values={"question": "latest release"},
            bindings=[
                ResolvedAgentActionBinding(
                    binding=NodeSystemAgentActionBinding(actionKey="web_search"),
                    source="node_config",
                )
            ],
            action_definitions={
                "web_search": ActionDefinition(
                    actionKey="web_search",
                    name="Web Search",
                    llmInstruction="Generate a query and run the action without summarizing results.",
                    llmOutputSchema=[ActionIoField(key="query", name="Query", valueType="text")],
                )
            },
        )

        self.assertIn("llmInstruction: Generate a query", prompt)
        self.assertNotIn("agentInstruction", prompt)

    def test_generate_agent_action_inputs_records_prompt_snapshot_metadata(self) -> None:
        def chat_with_local_model_with_meta_func(**kwargs):
            return ('{"web_search": {"query": "TooGraph"}}', {"warnings": [], "model": "test-model"})

        node = NodeSystemAgentNode.model_validate(
            {
                "kind": "agent",
                "ui": {"position": {"x": 0, "y": 0}},
                "reads": [{"state": "question"}],
                "writes": [{"state": "result_package"}],
                "config": {
                    "actionKey": "web_search",
                    "taskInstruction": "ACTION SECRET TASK",
                },
            }
        )

        _action_inputs, _state_outputs, _reasoning, _warnings, updated_config = generate_agent_action_inputs(
            node=node,
            input_values={"question": "ACTION SECRET INPUT"},
            bindings=[
                ResolvedAgentActionBinding(
                    binding=NodeSystemAgentActionBinding(actionKey="web_search"),
                    source="node_config",
                )
            ],
            action_definitions={
                "web_search": ActionDefinition(
                    actionKey="web_search",
                    name="Web Search",
                    llmOutputSchema=[ActionIoField(key="query", name="Query", valueType="text")],
                )
            },
            runtime_config={
                "resolved_provider_id": "local",
                "runtime_model_name": "test-model",
                "resolved_temperature": 0.2,
                "resolved_thinking": False,
                "resolved_thinking_level": "off",
            },
            chat_with_local_model_with_meta_func=chat_with_local_model_with_meta_func,
        )

        snapshot = updated_config["prompt_snapshots"][0]
        self.assertEqual(snapshot["phase"], "action_input_planning")
        self.assertTrue(snapshot["system_prompt_hash"].startswith("sha256:"))
        self.assertTrue(snapshot["user_prompt_hash"].startswith("sha256:"))
        self.assertEqual(snapshot["prompt_cache_policy"]["kind"], "prompt_cache_policy")
        self.assertEqual(snapshot["prompt_cache_policy"]["stable_prefix_hash"], snapshot["system_prompt_hash"])
        self.assertEqual(snapshot["prompt_cache_policy"]["dynamic_suffix_hash"], snapshot["user_prompt_hash"])
        self.assertEqual(snapshot["prompt_cache_policy"]["mode"], "audit_only")
        self.assertEqual(snapshot["prompt_cache_policy"]["provider_cache_control"], "not_applied")
        self.assertFalse(snapshot["prompt_cache_policy"]["eligible"])
        self.assertEqual(snapshot["prompt_cache_policy"]["reason"], "runtime_state_in_system_prompt")
        self.assertEqual(snapshot["prompt_cache_policy"]["invalidators"], ["input_state_keys", "action_keys"])
        self.assertEqual(snapshot["action_keys"], ["web_search"])
        serialized_snapshot = json.dumps(snapshot, ensure_ascii=False)
        self.assertNotIn("ACTION SECRET INPUT", serialized_snapshot)
        self.assertNotIn("ACTION SECRET TASK", serialized_snapshot)

    def test_generate_agent_action_inputs_records_provider_cost_budget_degradation(self) -> None:
        degradation = {
            "kind": "provider_cost_budget_degradation",
            "status": "applied",
            "requested_model_ref": "openai/gpt-primary",
            "selected_model_ref": "local/gpt-economy",
            "provider_cost_budget_preflight": {"status": "blocked", "on_exceeded": "degrade_model"},
        }

        def chat_with_model_ref_with_meta_func(**_kwargs):
            return (
                '{"web_search": {"query": "TooGraph"}}',
                {
                    "warnings": [],
                    "model": "gpt-economy",
                    "provider_id": "local",
                    "provider_cost_budget_degradation": degradation,
                },
            )

        node = NodeSystemAgentNode.model_validate(
            {
                "kind": "agent",
                "ui": {"position": {"x": 0, "y": 0}},
                "reads": [{"state": "question"}],
                "config": {"actionKey": "web_search"},
            }
        )

        _action_inputs, _state_outputs, _reasoning, warnings, updated_config = generate_agent_action_inputs(
            node=node,
            input_values={"question": "search"},
            bindings=[
                ResolvedAgentActionBinding(
                    binding=NodeSystemAgentActionBinding(actionKey="web_search"),
                    source="node_config",
                )
            ],
            action_definitions={
                "web_search": ActionDefinition(
                    actionKey="web_search",
                    name="Web Search",
                    llmOutputSchema=[ActionIoField(key="query", name="Query", valueType="text")],
                )
            },
            runtime_config={
                "resolved_provider_id": "openai",
                "runtime_model_name": "gpt-primary",
                "resolved_temperature": 0.2,
                "resolved_thinking": False,
                "resolved_thinking_level": "off",
                "resolved_model_ref": "openai/gpt-primary",
            },
            chat_with_model_ref_with_meta_func=chat_with_model_ref_with_meta_func,
        )

        self.assertEqual(warnings, [])
        self.assertEqual(updated_config["action_input_provider_cost_budget_degradation"], degradation)

    def test_action_input_prompt_separates_state_inputs_from_llm_parameters(self) -> None:
        prompt = build_action_input_system_prompt(
            input_values={"user_goal": "打开运行历史"},
            bindings=[
                ResolvedAgentActionBinding(
                    binding=NodeSystemAgentActionBinding(actionKey="toograph_page_operator"),
                    source="node_config",
                )
            ],
            action_definitions={
                "toograph_page_operator": ActionDefinition(
                    actionKey="toograph_page_operator",
                    name="TooGraph Page Operator",
                    stateInputSchema=[
                        ActionIoField(
                            key="user_goal",
                            name="User Goal",
                            valueType="text",
                            description="User goal read from graph state.",
                        )
                    ],
                    llmOutputSchema=[
                        ActionIoField(
                            key="commands",
                            name="Commands",
                            valueType="json",
                            description="Page operation commands generated by the LLM.",
                        )
                    ],
                )
            },
        )

        self.assertIn("stateInputSchema:", prompt)
        self.assertIn("description: User goal read from graph state.", prompt)
        self.assertIn("llmOutputSchema:", prompt)
        self.assertIn("description: Page operation commands generated by the LLM.", prompt)

    def test_action_input_prompt_includes_before_llm_context(self) -> None:
        with tempfile.TemporaryDirectory() as temp_dir:
            action_dir = Path(temp_dir) / "web_search"
            action_dir.mkdir()
            (action_dir / "before_llm.py").write_text(
                "import json\n"
                "print(json.dumps({'context': 'Current date: 2026-05-08'}))\n",
                encoding="utf-8",
            )
            prompt = build_action_input_system_prompt(
                input_values={"question": "最新模型发布日期"},
                bindings=[
                    ResolvedAgentActionBinding(
                        binding=NodeSystemAgentActionBinding(actionKey="web_search"),
                        source="node_config",
                    )
                ],
                action_definitions={
                    "web_search": ActionDefinition(
                        actionKey="web_search",
                        name="Web Search",
                        llmInstruction="Generate a query.",
                        llmOutputSchema=[ActionIoField(key="query", name="Query", valueType="text")],
                        sourcePath=str(action_dir / "action.json"),
                    )
                },
            )

        self.assertIn("== Action Pre-LLM Context ==", prompt)
        self.assertIn("actionKey: web_search", prompt)
        self.assertIn("Current date: 2026-05-08", prompt)

    def test_action_input_prompt_renders_managed_action_input_slots_by_field_key(self) -> None:
        node = NodeSystemAgentNode.model_validate(
            {
                "kind": "agent",
                "ui": {"position": {"x": 0, "y": 0}},
                "reads": [
                    {
                        "state": "source_text",
                        "binding": {
                            "kind": "action_input",
                            "actionKey": "summarize_text",
                            "fieldKey": "text",
                            "managed": True,
                        },
                    }
                ],
                "config": {"actionKey": "summarize_text"},
            }
        )

        prompt = build_action_input_system_prompt(
            input_values={"source_text": "Draft article body."},
            bindings=[
                ResolvedAgentActionBinding(
                    binding=NodeSystemAgentActionBinding(actionKey="summarize_text"),
                    source="node_config",
                )
            ],
            action_definitions={
                "summarize_text": ActionDefinition(
                    actionKey="summarize_text",
                    name="Summarize Text",
                    stateInputSchema=[ActionIoField(key="text", name="Text", valueType="text")],
                    llmOutputSchema=[ActionIoField(key="summary_style", name="Summary Style", valueType="text")],
                )
            },
            node=node,
        )

        self.assertIn("== Action State Input Slots ==", prompt)
        self.assertIn("- actionKey: summarize_text", prompt)
        self.assertIn("fieldKey: text", prompt)
        self.assertIn("source_state: source_text", prompt)
        self.assertIn("Draft article body.", prompt)

    def test_before_llm_receives_runtime_context_without_graph_state(self) -> None:
        with tempfile.TemporaryDirectory() as temp_dir:
            action_dir = Path(temp_dir) / "toograph_page_operator"
            action_dir.mkdir()
            (action_dir / "before_llm.py").write_text(
                "import json, sys\n"
                "payload = json.loads(sys.stdin.read() or '{}')\n"
                "context = {\n"
                "  'has_graph_state': 'graph_state' in payload,\n"
                "  'page_path': payload.get('runtime_context', {}).get('page_path'),\n"
                "}\n"
                "print(json.dumps({'context': json.dumps(context, ensure_ascii=False)}))\n",
                encoding="utf-8",
            )
            prompt = build_action_input_system_prompt(
                input_values={"page_path": "/stale-graph-state"},
                bindings=[
                    ResolvedAgentActionBinding(
                        binding=NodeSystemAgentActionBinding(actionKey="toograph_page_operator"),
                        source="node_config",
                    )
                ],
                action_definitions={
                    "toograph_page_operator": ActionDefinition(
                        actionKey="toograph_page_operator",
                        name="TooGraph Page Operator",
                        llmOutputSchema=[ActionIoField(key="commands", name="Commands", valueType="json")],
                        sourcePath=str(action_dir / "action.json"),
                    )
                },
                runtime_context={"page_path": "/editor"},
            )

        before_llm_context = prompt.split("== Action Pre-LLM Context ==", 1)[1]
        self.assertIn('"has_graph_state": false', before_llm_context)
        self.assertIn('"page_path": "/editor"', before_llm_context)
        self.assertNotIn("/stale-graph-state", before_llm_context)

    def test_before_llm_receives_managed_action_state_inputs(self) -> None:
        with tempfile.TemporaryDirectory() as temp_dir:
            action_dir = Path(temp_dir) / "local_workspace_executor"
            action_dir.mkdir()
            (action_dir / "before_llm.py").write_text(
                "import json, sys\n"
                "payload = json.loads(sys.stdin.read() or '{}')\n"
                "print(json.dumps({'context': json.dumps(payload.get('action_state_inputs', {}), ensure_ascii=False)}))\n",
                encoding="utf-8",
            )
            node = NodeSystemAgentNode.model_validate(
                {
                    "kind": "agent",
                    "ui": {"position": {"x": 0, "y": 0}},
                    "reads": [
                        {
                            "state": "workspace_request_state",
                            "binding": {
                                "kind": "action_input",
                                "actionKey": "local_workspace_executor",
                                "fieldKey": "workspace_request",
                                "managed": True,
                            },
                        }
                    ],
                    "config": {"actionKey": "local_workspace_executor"},
                }
            )
            prompt = build_action_input_system_prompt(
                input_values={"workspace_request_state": "写入 backend/data/tmp/example.txt"},
                bindings=[
                    ResolvedAgentActionBinding(
                        binding=NodeSystemAgentActionBinding(actionKey="local_workspace_executor"),
                        source="node_config",
                    )
                ],
                action_definitions={
                    "local_workspace_executor": ActionDefinition(
                        actionKey="local_workspace_executor",
                        name="Local Workspace Executor",
                        stateInputSchema=[ActionIoField(key="workspace_request", name="Workspace Request", valueType="text")],
                        llmOutputSchema=[ActionIoField(key="path", name="Path", valueType="text")],
                        sourcePath=str(action_dir / "action.json"),
                    )
                },
                node=node,
            )

        before_llm_context = prompt.split("== Action Pre-LLM Context ==", 1)[1]
        self.assertIn('"workspace_request": "写入 backend/data/tmp/example.txt"', before_llm_context)

    def test_action_input_prompt_passes_node_task_instruction_to_before_llm(self) -> None:
        with tempfile.TemporaryDirectory() as temp_dir:
            action_dir = Path(temp_dir) / "local_workspace_executor"
            action_dir.mkdir()
            (action_dir / "before_llm.py").write_text(
                "import json, sys\n"
                "payload = json.loads(sys.stdin.read() or '{}')\n"
                "print(json.dumps({'context': payload.get('task_instruction', '')}))\n",
                encoding="utf-8",
            )
            node = NodeSystemAgentNode.model_validate(
                {
                    "kind": "agent",
                    "ui": {"position": {"x": 0, "y": 0}},
                    "config": {
                        "actionKey": "local_workspace_executor",
                        "taskInstruction": "写入 backend/data/tmp/example.txt。",
                    },
                }
            )
            prompt = build_action_input_system_prompt(
                input_values={},
                bindings=[
                    ResolvedAgentActionBinding(
                        binding=NodeSystemAgentActionBinding(actionKey="local_workspace_executor"),
                        source="node_config",
                    )
                ],
                action_definitions={
                    "local_workspace_executor": ActionDefinition(
                        actionKey="local_workspace_executor",
                        name="Local Workspace Executor",
                        llmOutputSchema=[ActionIoField(key="path", name="Path", valueType="text")],
                        sourcePath=str(action_dir / "action.json"),
                    )
                },
                node=node,
            )

        self.assertIn("写入 backend/data/tmp/example.txt。", prompt)

    def test_capability_selector_prompt_uses_before_llm_context_for_catalog(self) -> None:
        with tempfile.TemporaryDirectory() as temp_dir:
            action_dir = Path(temp_dir) / "toograph_capability_selector"
            action_dir.mkdir()
            (action_dir / "before_llm.py").write_text(
                "import json\n"
                "print(json.dumps({'context': 'Available TooGraph capabilities:\\n"
                "Graph Templates:\\n- kind: subgraph\\n  key: advanced_web_research_loop\\n"
                "Actions:\\n- kind: action\\n  key: web_search'}))\n",
                encoding="utf-8",
            )
            prompt = build_action_input_system_prompt(
                input_values={"requirement": "帮我联网搜索资料"},
                bindings=[
                    ResolvedAgentActionBinding(
                        binding=NodeSystemAgentActionBinding(actionKey="toograph_capability_selector"),
                        source="node_config",
                    )
                ],
                action_definitions={
                    "toograph_capability_selector": ActionDefinition(
                        actionKey="toograph_capability_selector",
                        name="TooGraph Capability Selector",
                        stateInputSchema=[
                            ActionIoField(key="requirement", name="Requirement", valueType="text"),
                        ],
                        llmOutputSchema=[
                            ActionIoField(key="capability", name="Capability", valueType="capability"),
                        ],
                        stateOutputSchema=[ActionIoField(key="capability", name="Capability", valueType="capability")],
                        sourcePath=str(action_dir / "action.json"),
                        runtimeReady=True,
                        runtimeRegistered=True,
                    )
                },
            )

        self.assertIn("== Action Pre-LLM Context ==", prompt)
        self.assertIn("Available TooGraph capabilities:", prompt)
        self.assertIn("key: advanced_web_research_loop", prompt)
        self.assertIn("key: web_search", prompt)
        self.assertNotIn("== Available Capabilities ==", prompt)

    def test_action_input_prompt_uses_node_override_as_single_effective_instruction(self) -> None:
        node = NodeSystemAgentNode.model_validate(
            {
                "kind": "agent",
                "ui": {"position": {"x": 0, "y": 0}},
                "config": {
                    "actionKey": "web_search",
                    "taskInstruction": "Generate the search arguments.",
                    "actionInstructionBlocks": {
                        "web_search": {
                            "actionKey": "web_search",
                            "title": "联网搜索 action instruction",
                            "content": "Use the user-edited query rule.",
                            "source": "node.override",
                        }
                    },
                },
            }
        )

        system_prompt = build_action_input_system_prompt(
            input_values={"question": "latest release"},
            bindings=[
                ResolvedAgentActionBinding(
                    binding=NodeSystemAgentActionBinding(actionKey="web_search"),
                    source="node_config",
                )
            ],
            action_definitions={
                "web_search": ActionDefinition(
                    actionKey="web_search",
                    name="Web Search",
                    llmInstruction="Use the manifest query rule.",
                    llmOutputSchema=[ActionIoField(key="query", name="Query", valueType="text")],
                )
            },
            node=node,
        )
        user_prompt = build_action_input_user_prompt(node)

        self.assertIn("llmInstruction: Use the user-edited query rule.", system_prompt)
        self.assertNotIn("Use the manifest query rule.", system_prompt)
        self.assertEqual(user_prompt, "Generate the search arguments.")
        self.assertNotIn("Bound Action Instructions", user_prompt)

    def test_action_input_prompt_respects_blank_node_override(self) -> None:
        node = NodeSystemAgentNode.model_validate(
            {
                "kind": "agent",
                "ui": {"position": {"x": 0, "y": 0}},
                "config": {
                    "actionKey": "web_search",
                    "actionInstructionBlocks": {
                        "web_search": {
                            "actionKey": "web_search",
                            "title": "联网搜索 action instruction",
                            "content": "   ",
                            "source": "node.override",
                        }
                    },
                },
            }
        )

        system_prompt = build_action_input_system_prompt(
            input_values={"question": "latest release"},
            bindings=[
                ResolvedAgentActionBinding(
                    binding=NodeSystemAgentActionBinding(actionKey="web_search"),
                    source="node_config",
                )
            ],
            action_definitions={
                "web_search": ActionDefinition(
                    actionKey="web_search",
                    name="Web Search",
                    llmInstruction="Use the manifest query rule.",
                    llmOutputSchema=[ActionIoField(key="query", name="Query", valueType="text")],
                )
            },
            node=node,
        )

        self.assertNotIn("Use the manifest query rule.", system_prompt)
        self.assertNotIn("llmInstruction:", system_prompt)

    def test_action_input_prompt_does_not_expose_output_mapping_to_llm(self) -> None:
        prompt = build_action_input_system_prompt(
            input_values={"question": "latest release"},
            bindings=[
                ResolvedAgentActionBinding(
                    binding=NodeSystemAgentActionBinding(
                        actionKey="web_search",
                        outputMapping={
                            "query": "planned_query",
                            "source_urls": "search_sources",
                        },
                    ),
                    source="node_config",
                )
            ],
            action_definitions={
                "web_search": ActionDefinition(
                    actionKey="web_search",
                    name="Web Search",
                    llmOutputSchema=[ActionIoField(key="query", name="Query", valueType="text")],
                    stateOutputSchema=[
                        ActionIoField(key="query", name="Query", valueType="text", description="Executed query."),
                        ActionIoField(key="source_urls", name="Source URLs", valueType="json", description="Original URLs."),
                    ],
                )
            },
            state_schema={
                "planned_query": NodeSystemStateDefinition(
                    name="联网搜索 Query",
                    description="实际交给搜索 Action执行的查询语句。",
                    type=NodeSystemStateType.TEXT,
                ),
                "search_sources": NodeSystemStateDefinition(
                    name="联网搜索 Source URLs",
                    description="搜索 Action返回的原文网页 URL 列表。",
                    type=NodeSystemStateType.JSON,
                ),
            },
        )

        self.assertNotIn("== Bound Action Output Mapping ==", prompt)
        self.assertNotIn("outputKey: query", prompt)
        self.assertNotIn("targetState: planned_query", prompt)
        self.assertNotIn("targetName: 联网搜索 Query", prompt)
        self.assertIn("== Action LLM Output JSON Shape ==", prompt)
        self.assertIn('"web_search"', prompt)
        self.assertIn('"query"', prompt)

    def test_action_input_prompt_expands_result_package_inputs_before_planning_arguments(self) -> None:
        artifact = create_uploaded_capability_artifact(
            file_name="search-source.md",
            content_type="text/markdown",
            payload=b"Downloaded source text for the next action input.",
        )
        try:
            prompt = build_action_input_system_prompt(
                input_values={
                    "search_result": {
                        "kind": "result_package",
                        "sourceType": "action",
                        "sourceKey": "web_search",
                        "outputs": {
                            "artifact_paths": {
                                "name": "Artifact Paths",
                                "description": "Downloaded source documents.",
                                "type": "file",
                                "value": [artifact["local_path"]],
                            }
                        },
                    }
                },
                bindings=[
                    ResolvedAgentActionBinding(
                        binding=NodeSystemAgentActionBinding(actionKey="extract_facts"),
                        source="node_config",
                    )
                ],
                action_definitions={
                    "extract_facts": ActionDefinition(
                        actionKey="extract_facts",
                        name="Extract Facts",
                        llmOutputSchema=[ActionIoField(key="document_summary", name="Document Summary", valueType="text")],
                    )
                },
                state_schema={
                    "search_result": NodeSystemStateDefinition.model_validate(
                        {
                            "name": "Search Result",
                            "type": "result_package",
                        }
                    )
                },
            )

            self.assertIn("key: artifact_paths", prompt)
            self.assertIn("type: file", prompt)
            self.assertIn("Downloaded source text for the next action input.", prompt)
            self.assertNotIn(artifact["local_path"], prompt)
        finally:
            resolve_capability_artifact_path(artifact["local_path"]).unlink(missing_ok=True)

    def test_generate_action_inputs_passes_structured_output_schema_to_model(self) -> None:
        captured: dict[str, object] = {}

        def chat_with_local_model_with_meta_func(**kwargs):
            captured.update(kwargs)
            return ('{"web_search": {"query": "TooGraph structured output", "search_context": ""}}', {"warnings": []})

        node = NodeSystemAgentNode.model_validate(
            {
                "kind": "agent",
                "ui": {"position": {"x": 0, "y": 0}},
                "config": {
                    "actionKey": "web_search",
                    "taskInstruction": "Build search arguments.",
                },
            }
        )

        action_inputs, state_outputs, _reasoning, warnings, updated_config = generate_agent_action_inputs(
            node=node,
            input_values={"question": "How should LLM nodes emit JSON?"},
            bindings=[
                ResolvedAgentActionBinding(
                    binding=NodeSystemAgentActionBinding(actionKey="web_search"),
                    source="node_config",
                )
            ],
            action_definitions={
                "web_search": ActionDefinition(
                    actionKey="web_search",
                    name="Web Search",
                    llmOutputSchema=[
                        ActionIoField(
                            key="query",
                            name="Query",
                            valueType="text",
                            description="Search query.",
                        ),
                        ActionIoField(
                            key="search_context",
                            name="Search Context",
                            valueType="text",
                            description="Additional search context. Use an empty string when not needed.",
                        )
                    ],
                )
            },
            runtime_config={
                "resolved_provider_id": "local",
                "runtime_model_name": "test-model",
                "resolved_temperature": 0.2,
                "resolved_thinking": False,
                "resolved_thinking_level": "off",
            },
            chat_with_local_model_with_meta_func=chat_with_local_model_with_meta_func,
        )

        self.assertEqual(action_inputs, {"web_search": {"query": "TooGraph structured output", "search_context": ""}})
        self.assertEqual(state_outputs, {})
        self.assertEqual(warnings, [])
        schema = captured["structured_output_schema"]
        self.assertEqual(schema["type"], "object")
        self.assertEqual(schema["required"], ["web_search"])
        self.assertFalse(schema["additionalProperties"])
        self.assertEqual(schema["properties"]["web_search"]["required"], ["query", "search_context"])
        self.assertFalse(schema["properties"]["web_search"]["additionalProperties"])
        self.assertEqual(schema["properties"]["web_search"]["properties"]["query"]["type"], "string")
        self.assertEqual(updated_config["action_input_structured_output_strategy"], "json_schema")

    def test_generate_action_inputs_passes_on_delta_to_model(self) -> None:
        captured: dict[str, object] = {}
        on_delta = object()

        def chat_with_local_model_with_meta_func(**kwargs):
            captured.update(kwargs)
            return ('{"web_search": {"query": "TooGraph streaming"}}', {"warnings": []})

        node = NodeSystemAgentNode.model_validate(
            {
                "kind": "agent",
                "ui": {"position": {"x": 0, "y": 0}},
                "config": {
                    "actionKey": "web_search",
                    "taskInstruction": "Build search arguments.",
                },
            }
        )

        generate_agent_action_inputs(
            node=node,
            input_values={"question": "How should action planning stream?"},
            bindings=[
                ResolvedAgentActionBinding(
                    binding=NodeSystemAgentActionBinding(actionKey="web_search"),
                    source="node_config",
                )
            ],
            action_definitions={
                "web_search": ActionDefinition(
                    actionKey="web_search",
                    name="Web Search",
                    llmOutputSchema=[
                        ActionIoField(
                            key="query",
                            name="Query",
                            valueType="text",
                            description="Search query.",
                        )
                    ],
                )
            },
            runtime_config={
                "resolved_provider_id": "local",
                "runtime_model_name": "test-model",
                "resolved_temperature": 0.2,
                "resolved_thinking": False,
                "resolved_thinking_level": "off",
            },
            chat_with_local_model_with_meta_func=chat_with_local_model_with_meta_func,
            on_delta=on_delta,
        )

        self.assertIs(captured["on_delta"], on_delta)

    def test_generate_action_inputs_returns_custom_state_outputs_in_node_write_order(self) -> None:
        captured: dict[str, object] = {}

        def chat_with_local_model_with_meta_func(**kwargs):
            captured.update(kwargs)
            return (
                json.dumps(
                    {
                        "web_search": {"query": "TooGraph RAG"},
                        "planner_notes": "Use recent docs first.",
                        "draft_answer": "Draft response.",
                    }
                ),
                {"warnings": []},
            )

        node = NodeSystemAgentNode.model_validate(
            {
                "kind": "agent",
                "ui": {"position": {"x": 0, "y": 0}},
                "writes": [
                    {"state": "planner_notes", "mode": "replace"},
                    {"state": "source_documents", "mode": "replace"},
                    {"state": "draft_answer", "mode": "replace"},
                ],
                "config": {
                    "actionKey": "web_search",
                    "taskInstruction": "Plan search arguments and draft intermediate outputs.",
                    "actionBindings": [
                        {
                            "actionKey": "web_search",
                            "outputMapping": {"source_documents": "source_documents"},
                        }
                    ],
                },
            }
        )
        state_schema = {
            "planner_notes": NodeSystemStateDefinition.model_validate(
                {
                    "name": "Planner Notes",
                    "description": "Reasoning notes for the next LLM node.",
                    "type": "markdown",
                }
            ),
            "source_documents": NodeSystemStateDefinition.model_validate({"name": "Source Documents", "type": "json"}),
            "draft_answer": NodeSystemStateDefinition.model_validate(
                {
                    "name": "Draft Answer",
                    "description": "Intermediate user-facing draft.",
                    "type": "markdown",
                }
            ),
        }

        action_inputs, state_outputs, _reasoning, warnings, updated_config = generate_agent_action_inputs(
            node=node,
            input_values={"question": "Explain TooGraph RAG"},
            bindings=[
                ResolvedAgentActionBinding(
                    binding=NodeSystemAgentActionBinding(
                        actionKey="web_search",
                        outputMapping={"source_documents": "source_documents"},
                    ),
                    source="node_config",
                )
            ],
            action_definitions={
                "web_search": ActionDefinition(
                    actionKey="web_search",
                    name="Web Search",
                    llmOutputSchema=[ActionIoField(key="query", name="Query", valueType="text")],
                    stateOutputSchema=[ActionIoField(key="source_documents", name="Source Documents", valueType="json")],
                )
            },
            runtime_config={
                "resolved_provider_id": "local",
                "runtime_model_name": "test-model",
                "resolved_temperature": 0.2,
                "resolved_thinking": False,
                "resolved_thinking_level": "off",
            },
            state_schema=state_schema,
            chat_with_local_model_with_meta_func=chat_with_local_model_with_meta_func,
        )

        self.assertEqual(action_inputs, {"web_search": {"query": "TooGraph RAG"}})
        self.assertEqual(
            state_outputs,
            {
                "planner_notes": "Use recent docs first.",
                "draft_answer": "Draft response.",
            },
        )
        self.assertEqual(warnings, [])
        schema = captured["structured_output_schema"]
        self.assertEqual(list(schema["properties"].keys()), ["web_search", "planner_notes", "draft_answer"])
        self.assertEqual(schema["required"], ["web_search", "planner_notes", "draft_answer"])
        prompt = captured["system_prompt"]
        self.assertIn("== Custom LLM State Outputs ==", prompt)
        self.assertIn("These state outputs are written directly to graph state and are not passed to after_llm.py.", prompt)
        self.assertLess(prompt.index("stateKey: planner_notes"), prompt.index("stateKey: draft_answer"))
        self.assertEqual(updated_config["action_input_state_output_keys"], ["planner_notes", "draft_answer"])

    def test_repairs_invalid_action_inputs_without_original_prompt_context(self) -> None:
        calls: list[dict[str, object]] = []

        def chat_with_local_model_with_meta_func(**kwargs):
            calls.append(dict(kwargs))
            if len(calls) == 1:
                return ('{"web_search": {"query": 7}}', {"warnings": [], "model": "test-model"})
            return ('{"web_search": {"query": "repaired query"}}', {"warnings": [], "model": "test-model"})

        node = NodeSystemAgentNode.model_validate(
            {
                "kind": "agent",
                "ui": {"position": {"x": 0, "y": 0}},
                "config": {
                    "actionKey": "web_search",
                    "taskInstruction": "ORIGINAL ACTION TASK",
                },
            }
        )

        action_inputs, state_outputs, _reasoning, warnings, updated_config = generate_agent_action_inputs(
            node=node,
            input_values={"question": "ORIGINAL SECRET INPUT"},
            bindings=[
                ResolvedAgentActionBinding(
                    binding=NodeSystemAgentActionBinding(actionKey="web_search"),
                    source="node_config",
                )
            ],
            action_definitions={
                "web_search": ActionDefinition(
                    actionKey="web_search",
                    name="Web Search",
                    llmOutputSchema=[
                        ActionIoField(
                            key="query",
                            name="Query",
                            valueType="text",
                            description="Search query.",
                        )
                    ],
                )
            },
            runtime_config={
                "resolved_provider_id": "local",
                "runtime_model_name": "test-model",
                "resolved_temperature": 0.2,
                "resolved_thinking": False,
                "resolved_thinking_level": "off",
            },
            chat_with_local_model_with_meta_func=chat_with_local_model_with_meta_func,
        )

        self.assertEqual(action_inputs, {"web_search": {"query": "repaired query"}})
        self.assertEqual(state_outputs, {})
        self.assertEqual(warnings, [])
        self.assertEqual(len(calls), 2)
        repair_call = calls[1]
        repair_prompt = f"{repair_call['system_prompt']}\n{repair_call['user_prompt']}"
        self.assertIn("JSON repair step", str(repair_call["system_prompt"]))
        self.assertIn("target_schema", str(repair_call["user_prompt"]))
        self.assertIn("validation_errors", str(repair_call["user_prompt"]))
        self.assertIn("raw_model_output", str(repair_call["user_prompt"]))
        repair_payload = json.loads(str(repair_call["user_prompt"]))
        self.assertEqual(repair_payload["raw_model_output"], '{"web_search": {"query": 7}}')
        self.assertNotIn("ORIGINAL SECRET INPUT", repair_prompt)
        self.assertNotIn("ORIGINAL ACTION TASK", repair_prompt)
        self.assertEqual(repair_call["thinking_level"], "off")
        self.assertTrue(updated_config["action_input_structured_output_repair_attempted"])
        self.assertTrue(updated_config["action_input_structured_output_repair_succeeded"])
        self.assertEqual(updated_config["action_input_structured_output_validation_errors"], [])
        self.assertIn(
            "$.web_search.query expected string",
            updated_config["action_input_structured_output_initial_validation_errors"][0],
        )
        snapshots = updated_config["prompt_snapshots"]
        self.assertEqual(
            [snapshot["phase"] for snapshot in snapshots],
            ["action_input_planning", "action_input_structured_output_repair"],
        )
        repair_snapshot = snapshots[1]
        self.assertTrue(repair_snapshot["system_prompt_hash"].startswith("sha256:"))
        self.assertTrue(repair_snapshot["user_prompt_hash"].startswith("sha256:"))
        self.assertEqual(repair_snapshot["action_keys"], ["web_search"])
        serialized_repair_snapshot = json.dumps(repair_snapshot, ensure_ascii=False)
        self.assertNotIn('{"web_search": {"query": 7}}', serialized_repair_snapshot)
        self.assertNotIn("ORIGINAL SECRET INPUT", serialized_repair_snapshot)
        self.assertNotIn("ORIGINAL ACTION TASK", serialized_repair_snapshot)


if __name__ == "__main__":
    unittest.main()
