import test from "node:test";
import assert from "node:assert/strict";
import { readFileSync } from "node:fs";
import { dirname, resolve } from "node:path";
import { fileURLToPath } from "node:url";

const currentDirectory = dirname(fileURLToPath(import.meta.url));
const pageSource = readFileSync(resolve(currentDirectory, "ModelLogsPage.vue"), "utf8");

test("ModelLogsPage renders a themed paginated raw model request log", () => {
  assert.match(pageSource, /<AppShell>/);
  assert.match(pageSource, /class="model-logs-page"/);
  assert.match(pageSource, /fetchModelLogs/);
  assert.match(pageSource, /updateModelLogRetention/);
  assert.match(pageSource, /<ElInputNumber[\s\S]*v-model="retentionRootRuns"/);
  assert.match(pageSource, /<ElInput[\s\S]*v-model="query"/);
  assert.match(pageSource, /<ElPagination[\s\S]*v-model:current-page="currentPage"[\s\S]*:page-size="pageSize"[\s\S]*:total="total"/);
  assert.match(pageSource, /model-logs-page__tree-node/);
  assert.match(pageSource, /v-for="item in treeItems"/);
  assert.match(pageSource, /selectTreeItem\(item\)/);
  assert.match(pageSource, /runTrees/);
  assert.match(pageSource, /flattenTreeItems/);
  assert.match(pageSource, /model-logs-page__tree-children/);
  assert.match(pageSource, /model-logs-page__retention/);
  assert.match(pageSource, /model-logs-page__request-raw/);
  assert.match(pageSource, /model-logs-page__response-raw/);
  assert.doesNotMatch(pageSource, /<details open class="model-logs-page__raw-panel/);
  assert.match(pageSource, /@click="openRawDialog\('request'\)"/);
  assert.match(pageSource, /@click="openRawDialog\('response'\)"/);
  assert.match(pageSource, /model-logs-page__raw-summary/);
  assert.match(pageSource, /rawRequestHint/);
  assert.match(pageSource, /rawResponseHint/);
  assert.match(pageSource, /<ElDialog[\s\S]*v-model="rawDialogVisible"[\s\S]*class="model-logs-page__raw-dialog"/);
  assert.match(pageSource, /const rawDialogKind = ref<"request" \| "response">\("request"\);/);
  assert.match(pageSource, /function openRawDialog\(kind: "request" \| "response"\)/);
  assert.match(pageSource, /const rawDialogContent = computed/);
  assert.match(pageSource, /getStreamSummary/);
  assert.match(pageSource, /selectedStreamSummary/);
  assert.match(pageSource, /streamMerged/);
  assert.match(pageSource, /hasStreamRaw/);
  assert.match(pageSource, /model-logs-page__raw-text/);
  assert.match(pageSource, /outputDisplayMode/);
  assert.match(pageSource, /outputMode/);
  assert.match(pageSource, /outputNormal/);
  assert.match(pageSource, /outputChunks/);
  assert.match(pageSource, /model-logs-page__output-chunk/);
  assert.match(pageSource, /formatStreamEventLabel/);
  assert.match(pageSource, /formatStreamEvent/);
  assert.match(pageSource, /rawResponseDisplayMode/);
  assert.match(pageSource, /rawResponseNormal/);
  assert.match(pageSource, /rawResponseChunks/);
  assert.match(pageSource, /formatResponseNormalRaw/);
  assert.match(pageSource, /delete normalized\._stream/);
  assert.match(pageSource, /model-logs-page__stream-event/);
  assert.match(pageSource, /rawStreamSource/);
  assert.match(pageSource, /formatReadableContent/);
  assert.match(pageSource, /formatReadableReasoning/);
  assert.match(pageSource, /formatRequestThinking/);
  assert.match(pageSource, /requestThinking/);
  assert.match(pageSource, /buildProviderRateReservationDiagnostic/);
  assert.match(pageSource, /buildProviderCredentialDiagnostic/);
  assert.match(pageSource, /buildProviderCostDiagnostic/);
  assert.match(pageSource, /buildProviderCostBudgetDegradationDiagnostic/);
  assert.match(pageSource, /buildProviderRateDecisionDiagnostic/);
  assert.match(pageSource, /buildProviderCacheDiagnostic/);
  assert.match(pageSource, /buildProviderFallbackDiagnostic/);
  assert.match(pageSource, /selectedRateReservation/);
  assert.match(pageSource, /selectedProviderCredential/);
  assert.match(pageSource, /selectedProviderCost/);
  assert.match(pageSource, /selectedProviderCostBudgetDegradation/);
  assert.match(pageSource, /selectedProviderRateDecision/);
  assert.match(pageSource, /selectedProviderCache/);
  assert.match(pageSource, /selectedProviderFallback/);
  assert.match(pageSource, /model-logs-page__rate-reservation/);
  assert.match(pageSource, /model-logs-page__provider-credential/);
  assert.match(pageSource, /model-logs-page__provider-cost/);
  assert.match(pageSource, /model-logs-page__provider-cost-budget-degradation/);
  assert.match(pageSource, /model-logs-page__provider-rate-decision/);
  assert.match(pageSource, /model-logs-page__provider-cache/);
  assert.match(pageSource, /model-logs-page__provider-fallback/);
  assert.match(pageSource, /model-logs-page__diagnostic-grid/);
  assert.match(pageSource, /model-logs-page__diagnostic-chips/);
  assert.match(pageSource, /rateReservationMetricLabel/);
  assert.match(pageSource, /rateReservationTimelineLabel/);
  assert.match(pageSource, /providerCredentialMetricLabel/);
  assert.match(pageSource, /providerCredentialTimelineLabel/);
  assert.match(pageSource, /providerCostMetricLabel/);
  assert.match(pageSource, /providerCostBudgetDegradationMetricLabel/);
  assert.match(pageSource, /providerRateDecisionMetricLabel/);
  assert.match(pageSource, /providerCacheMetricLabel/);
  assert.match(pageSource, /providerFallbackMetricLabel/);
  assert.match(pageSource, /\.model-logs-page__diagnostic-grid dd \{[^}]*overflow-wrap: anywhere/);
  assert.match(pageSource, /JSON\.stringify\(selectedLog\.request_raw, null, 2\)/);
  assert.match(pageSource, /JSON\.stringify\(selectedLog\.response_raw, null, 2\)/);
  assert.match(pageSource, /v-html="highlightJson\(rawDialogContent\)"/);
  assert.match(pageSource, /import \{ highlightJson \} from "\.\/modelLogsJsonHighlight\.ts";/);
  assert.match(pageSource, /model-logs-page__json-key/);
  assert.match(pageSource, /model-logs-page__json-string/);
  assert.match(pageSource, /model-logs-page__json-number/);
  assert.match(pageSource, /model-logs-page__json-boolean/);
  assert.match(pageSource, /model-logs-page__json-null/);
  assert.match(pageSource, /model-logs-page__json-string--multiline/);
  assert.match(pageSource, /model-logs-page__json-string-lines/);
  assert.match(pageSource, /model-logs-page__json-string-line/);
  assert.doesNotMatch(pageSource, /model-logs-page__json-line-break/);
  assert.match(pageSource, /v-for="message in selectedLog\.messages"/);
  assert.match(pageSource, /log\.reasoning/);
  assert.match(pageSource, /log\.content/);
  assert.match(pageSource, /\.model-logs-page__workspace \{[\s\S]*align-items:\s*stretch;/);
  assert.match(pageSource, /\.model-logs-page__entry-list \{[\s\S]*height:\s*100%;[\s\S]*max-height:\s*none;/);
  assert.match(pageSource, /\.model-logs-page__pagination :deep\(\.el-pagination\) \{[\s\S]*--el-color-primary:\s*rgb\(154,\s*52,\s*18\);/);
  assert.match(pageSource, /\.model-logs-page__pagination :deep\(\.btn-prev\),[\s\S]*\.model-logs-page__pagination :deep\(\.btn-next\),[\s\S]*\.model-logs-page__pagination :deep\(\.el-pager li\) \{[\s\S]*border-radius:\s*999px;/);
  assert.match(pageSource, /\.model-logs-page__pagination :deep\(\.el-pager li\.is-active\) \{[\s\S]*box-shadow:\s*0 8px 16px rgba\(120,\s*53,\s*15,\s*0\.12\);/);
  assert.match(pageSource, /\.model-logs-page__raw-grid \{[\s\S]*grid-template-columns:\s*repeat\(2,\s*minmax\(0,\s*1fr\)\);/);
  assert.match(pageSource, /\.model-logs-page__diagnostic-grid \{[\s\S]*grid-template-columns:\s*repeat\(4,\s*minmax\(0,\s*1fr\)\);/);
  assert.match(pageSource, /\.model-logs-page__diagnostic-chips span \{[\s\S]*font-family:\s*var\(--toograph-font-mono\);/);
  assert.match(pageSource, /\.model-logs-page__section-pill--danger \{[\s\S]*color:\s*rgb\(185,\s*28,\s*28\);/);
  assert.match(pageSource, /\.model-logs-page__raw-dialog-code \{[\s\S]*min-height:\s*420px;[\s\S]*overflow:\s*auto;/);
  assert.match(pageSource, /\.model-logs-page__message p \{[\s\S]*max-height:\s*220px;[\s\S]*overflow:\s*auto;/);
  assert.match(pageSource, /\.model-logs-page__output-chunk:nth-child\(odd\)/);
  assert.match(pageSource, /\.model-logs-page__output-chunk:nth-child\(even\)/);
  assert.match(pageSource, /\.model-logs-page__stream-raw \{[\s\S]*overflow:\s*auto;/);
  assert.match(pageSource, /@media \(max-width:\s*980px\) \{[\s\S]*\.model-logs-page__raw-grid \{[\s\S]*grid-template-columns:\s*1fr;/);
  assert.doesNotMatch(pageSource, /LM Core Monitor/);
});
