import test from "node:test";
import assert from "node:assert/strict";
import { readFileSync } from "node:fs";
import { dirname, resolve } from "node:path";
import { fileURLToPath } from "node:url";

const currentDirectory = dirname(fileURLToPath(import.meta.url));
const pageSource = readFileSync(resolve(currentDirectory, "ModelLogsPage.vue"), "utf8");

test("ModelLogsPage renders a themed paginated raw model request log", () => {
  assert.match(pageSource, /<AppShell>/);
  assert.match(pageSource, /class="model-logs-page"/);
  assert.match(pageSource, /fetchModelLogs/);
  assert.match(pageSource, /<ElInput[\s\S]*v-model="query"/);
  assert.match(pageSource, /<ElPagination[\s\S]*v-model:current-page="currentPage"[\s\S]*:page-size="pageSize"[\s\S]*:total="total"/);
  assert.match(pageSource, /model-logs-page__entry/);
  assert.match(pageSource, /model-logs-page__request-raw/);
  assert.match(pageSource, /model-logs-page__response-raw/);
  assert.match(pageSource, /<details open class="model-logs-page__raw-panel model-logs-page__request-raw">/);
  assert.match(pageSource, /<details open class="model-logs-page__raw-panel model-logs-page__response-raw">/);
  assert.match(pageSource, /model-logs-page__raw-summary/);
  assert.match(pageSource, /rawRequestHint/);
  assert.match(pageSource, /rawResponseHint/);
  assert.match(pageSource, /getStreamSummary/);
  assert.match(pageSource, /selectedStreamSummary/);
  assert.match(pageSource, /streamMerged/);
  assert.match(pageSource, /hasStreamRaw/);
  assert.match(pageSource, /model-logs-page__raw-text/);
  assert.match(pageSource, /outputDisplayMode/);
  assert.match(pageSource, /outputMode/);
  assert.match(pageSource, /outputNormal/);
  assert.match(pageSource, /outputChunks/);
  assert.match(pageSource, /model-logs-page__output-chunk/);
  assert.match(pageSource, /formatStreamEventLabel/);
  assert.match(pageSource, /formatStreamEvent/);
  assert.match(pageSource, /model-logs-page__stream-event/);
  assert.match(pageSource, /rawStreamSource/);
  assert.match(pageSource, /formatReadableContent/);
  assert.match(pageSource, /formatReadableReasoning/);
  assert.match(pageSource, /JSON\.stringify\(selectedLog\.request_raw, null, 2\)/);
  assert.match(pageSource, /JSON\.stringify\(selectedLog\.response_raw, null, 2\)/);
  assert.match(pageSource, /v-html="highlightJson\(formatRequestRaw\(selectedLog\)\)"/);
  assert.match(pageSource, /v-html="highlightJson\(formatResponseRaw\(selectedLog\)\)"/);
  assert.match(pageSource, /import \{ highlightJson \} from "\.\/modelLogsJsonHighlight\.ts";/);
  assert.match(pageSource, /model-logs-page__json-key/);
  assert.match(pageSource, /model-logs-page__json-string/);
  assert.match(pageSource, /model-logs-page__json-number/);
  assert.match(pageSource, /model-logs-page__json-boolean/);
  assert.match(pageSource, /model-logs-page__json-null/);
  assert.match(pageSource, /model-logs-page__json-string--multiline/);
  assert.match(pageSource, /model-logs-page__json-string-lines/);
  assert.match(pageSource, /model-logs-page__json-string-line/);
  assert.doesNotMatch(pageSource, /model-logs-page__json-line-break/);
  assert.match(pageSource, /v-for="message in selectedLog\.messages"/);
  assert.match(pageSource, /log\.reasoning/);
  assert.match(pageSource, /log\.content/);
  assert.match(pageSource, /\.model-logs-page__raw-grid \{[\s\S]*grid-template-columns:\s*repeat\(2,\s*minmax\(0,\s*1fr\)\);/);
  assert.match(pageSource, /\.model-logs-page__raw-panel \{[\s\S]*max-height:\s*560px;/);
  assert.match(pageSource, /\.model-logs-page__raw-panel pre \{[\s\S]*overflow:\s*auto;/);
  assert.match(pageSource, /\.model-logs-page__output-chunk:nth-child\(odd\)/);
  assert.match(pageSource, /\.model-logs-page__output-chunk:nth-child\(even\)/);
  assert.match(pageSource, /\.model-logs-page__stream-raw \{[\s\S]*overflow:\s*auto;/);
  assert.match(pageSource, /@media \(max-width:\s*980px\) \{[\s\S]*\.model-logs-page__raw-grid \{[\s\S]*grid-template-columns:\s*1fr;/);
  assert.doesNotMatch(pageSource, /LM Core Monitor/);
});
