import test from "node:test";
import assert from "node:assert/strict";
import { readFileSync } from "node:fs";
import { dirname, resolve } from "node:path";
import { fileURLToPath } from "node:url";

const currentFilePath = fileURLToPath(import.meta.url);
const currentDirectory = dirname(currentFilePath);
const componentSource = readFileSync(resolve(currentDirectory, "StateEditorPopover.vue"), "utf8");

test("StateEditorPopover uses compact metadata-first editing with Element Plus selects", () => {
  assert.match(componentSource, /import \{ computed, nextTick, ref \} from "vue";/);
  assert.match(componentSource, /import \{ ElInput, ElOption, ElSelect \} from "element-plus";/);
  assert.match(componentSource, /<span class="node-state-editor__field-label">Key<\/span>[\s\S]*<span class="node-state-editor__field-label">Name<\/span>/);
  assert.match(componentSource, /<span class="node-state-editor__field-label">Type<\/span>[\s\S]*<span class="node-state-editor__field-label">Color<\/span>/);
  assert.match(componentSource, /class="node-state-editor__grid"/);
  assert.match(componentSource, /\.node-state-editor__grid \{[\s\S]*grid-template-columns:\s*repeat\(2,\s*minmax\(0,\s*1fr\)\);/);
  assert.match(componentSource, /\.node-state-editor \{[\s\S]*border-radius:\s*14px;/);
  assert.match(componentSource, /\.node-state-editor \{[\s\S]*background:\s*rgba\(255,\s*244,\s*232,\s*0\.96\);/);
  assert.match(componentSource, /\.node-state-editor \{[\s\S]*padding:\s*12px;/);
  assert.match(componentSource, /\.node-state-editor \{[\s\S]*border:\s*1px solid rgba\(154,\s*52,\s*18,\s*0\.14\);/);
  assert.match(componentSource, /\.node-state-editor \{[\s\S]*box-shadow:\s*0 16px 34px rgba\(60,\s*41,\s*20,\s*0\.12\);/);
  assert.match(componentSource, /<ElSelect[\s\S]*ref="typeSelectRef"[\s\S]*class="node-state-editor__type-select"[\s\S]*:teleported="false"[\s\S]*popper-class="node-state-editor__select-popper"/);
  assert.match(componentSource, /<ElSelect[\s\S]*ref="colorSelectRef"[\s\S]*class="node-state-editor__color-select"[\s\S]*:teleported="false"[\s\S]*popper-class="node-state-editor__select-popper"/);
  assert.match(componentSource, /<ElSelect[\s\S]*aria-label="Type"/);
  assert.match(componentSource, /<ElSelect[\s\S]*aria-label="Color"/);
  assert.doesNotMatch(componentSource, /<label class="node-state-editor__field">[\s\S]*?<ElSelect/);
  assert.match(componentSource, /class="node-state-editor__color-select-value"/);
  assert.match(componentSource, /class="node-state-editor__color-dot" :style="selectedColorStyle"/);
  assert.match(componentSource, /v-for="option in colorOptions"/);
  assert.match(componentSource, /const typeSelectRef = ref<\{ blur\?: \(\) => void; toggleMenu\?: \(\) => void; expanded\?: boolean \} \| null>\(null\);/);
  assert.match(componentSource, /const colorSelectRef = ref<\{ blur\?: \(\) => void; toggleMenu\?: \(\) => void; expanded\?: boolean \} \| null>\(null\);/);
  assert.match(componentSource, /async function collapseSelectMenu\(selectRef:/);
  assert.match(componentSource, /if \(selectRef\.value\?\.expanded\) \{[\s\S]*selectRef\.value\.toggleMenu\?\.\(\);[\s\S]*\}/);
  assert.match(componentSource, /selectRef\.value\?\.blur\?\.\(\);/);
  assert.match(componentSource, /await collapseSelectMenu\(typeSelectRef\);/);
  assert.match(componentSource, /await collapseSelectMenu\(colorSelectRef\);/);
  assert.match(componentSource, /:deep\(.node-state-editor \.el-input__wrapper\),[\s\S]*background:\s*rgba\(255,\s*251,\s*246,\s*0\.88\);/);
  assert.match(componentSource, /:deep\(.node-state-editor \.el-textarea__inner\) \{[\s\S]*background:\s*rgba\(255,\s*251,\s*246,\s*0\.88\);/);
  assert.match(componentSource, /:deep\(.node-state-editor__select-popper\.el-popper\) \{[\s\S]*border-radius:\s*16px;/);
  assert.match(componentSource, /:deep\(.node-state-editor__select-popper\.el-popper\) \{[\s\S]*background:\s*rgba\(255,\s*248,\s*240,\s*0\.98\);/);
  assert.match(componentSource, /:deep\(.node-state-editor__select-popper \.el-select-dropdown__item\.is-selected\) \{[\s\S]*color:\s*#9a3412;/);
  assert.doesNotMatch(componentSource, /class="node-state-editor__actions"/);
  assert.doesNotMatch(componentSource, /node-state-editor__action-button/);
  assert.doesNotMatch(componentSource, /<ElButton/);
  assert.doesNotMatch(componentSource, />Cancel</);
  assert.doesNotMatch(componentSource, />Save</);
  assert.doesNotMatch(componentSource, />Value</);
  assert.doesNotMatch(componentSource, /\(event: "cancel"\)/);
  assert.doesNotMatch(componentSource, /\(event: "save"\)/);
});
